### ISSUE TITLE
Suggestion for Plugin Enhancement

### ISSUE THREAD

**Issue by andywu1998** [nnshi-s/obsidian-vocabulary-view-plugin#5]
Hi there,

I hope this email finds you well. I wanted to share an idea I had regarding your plugin.

While using the plugin, I often find myself browsing through various documents and coming across unfamiliar words. It would be incredibly useful if there was a feature that allowed me to select a word and quickly append it to my vocabulary file by running a command. This way, I can effortlessly expand my vocabulary while reading.

I understand that this is just an idea, but if you have any plans to update or enhance the plugin in the future, I kindly request you to consider incorporating this feature. I believe it would greatly benefit users like myself who are eager to improve their language skills.

Thank you so much for your dedication and effort in developing this plugin. Your work is greatly appreciated.

Best regards

**Comment by nnshi-s** [comment]
Thanks for your advice!
I have added a **Vocabulary Book** feature to the latest version of the plugin, please check it out.

You can create a new blank .md file, or designate an existing blank .md file as a vocabulary book. Within the `vocaview` blocks, you can add words to the vocabulary book or remove words from it. The vocabulary book itself is just another .md file with `vocaview` blocks.

To use this feature:
1. Go to the settings page of this plugin.
2. Change the **Number of Vocabulary Books** setting from 0 to a desired number.
3. Fill in the **Relative Path** for each vocabulary book. (Alternatively, you can right-click on an .md file in Obsidian, select `Copy Obsidian URL`, and paste it as the path.)
4. Close the settings page and reopen the file with `vocaview` blocks to refresh the display.

To disable this feature:
1. Go to the settings page of this plugin.
2. Change the **Number of Vocabulary Books** setting back to 0.
3. Close the settings page and reopen the file with `vocaview` blocks to refresh the display.
